project_name: apitest

base:
  url: https://www.wanandroid.com

email:
  send_user: 2209258481@qq.com
  email_host: smtp.qq.com
  stamp_key: rguixjpdqljsecfh
  send_list: 821046174@qq.com

test: git back